import { Minus, Plus, Trash2 } from 'lucide-react'
import { Link, useNavigate } from 'react-router-dom'
import { useCart } from '../context/CartContext'

export default function CartPage() {
  const navigate = useNavigate()
  const { cartItems, subtotal, updateQuantity, removeFromCart } = useCart()
  if (!cartItems.length) return <section className="mx-auto max-w-7xl px-4 py-24 text-center"><p className="text-sm font-bold uppercase tracking-[.14em] text-emerald-700">Your bag</p><h1 className="mt-3 text-4xl">Your cart is empty.</h1><Link to="/shop" className="mt-8 inline-block bg-stone-900 px-5 py-3 font-bold text-white">Browse products</Link></section>
  return <section className="mx-auto max-w-7xl px-4 py-12 sm:px-6 lg:px-8"><p className="text-sm font-bold uppercase tracking-[.14em] text-emerald-700">Your bag</p><h1 className="mt-2 text-4xl">Shopping cart</h1><div className="mt-9 grid gap-10 lg:grid-cols-[minmax(0,1fr)_22rem]"><div className="divide-y divide-stone-200 border-y border-stone-200">{cartItems.map((item) => <article key={item.id} className="grid grid-cols-[5.5rem_1fr] gap-4 py-5 sm:grid-cols-[7rem_1fr_auto] sm:gap-6"><Link to={`/products/${item.id}`}><img src={item.image} alt={item.name} className="aspect-square w-full object-cover" /></Link><div><p className="text-xs font-bold uppercase tracking-[.14em] text-emerald-700">{item.category}</p><Link to={`/products/${item.id}`} className="mt-1 block font-bold">{item.name}</Link><p className="mt-2 text-sm text-stone-600">${item.price.toFixed(2)}</p><div className="mt-4 flex items-center gap-3"><div className="flex items-center border border-stone-300"><button type="button" onClick={() => updateQuantity(item.id, item.quantity - 1)} className="grid h-9 w-9 place-items-center" aria-label={`Reduce ${item.name} quantity`}><Minus size={15} /></button><span className="grid h-9 min-w-9 place-items-center border-x border-stone-300 text-sm font-bold">{item.quantity}</span><button type="button" onClick={() => updateQuantity(item.id, item.quantity + 1)} disabled={item.quantity >= item.stock} className="grid h-9 w-9 place-items-center disabled:text-stone-300" aria-label={`Increase ${item.name} quantity`}><Plus size={15} /></button></div><button type="button" onClick={() => removeFromCart(item.id)} className="text-stone-500 hover:text-red-700" aria-label={`Remove ${item.name}`}><Trash2 size={18} /></button></div></div><p className="col-start-2 text-right font-bold sm:col-start-auto">${(item.price * item.quantity).toFixed(2)}</p></article>)}</div><aside className="h-fit bg-stone-100 p-6"><h2 className="text-xl">Order summary</h2><div className="mt-6 flex justify-between border-b border-stone-300 pb-4"><span>Subtotal</span><strong>${subtotal.toFixed(2)}</strong></div><button type="button" onClick={() => navigate('/checkout')} className="mt-7 w-full bg-stone-900 px-5 py-4 font-bold text-white hover:bg-emerald-800">Checkout</button></aside></div></section>
}